name: cooljeanius/emacs-apple
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.1
    - run: brew update
    - run: brew install make automake gettext texinfo gawk gdb coreutils
    - name: Initial build
      run: |
        sh ./autogen.sh
        ./configure --enable-silent-rules --disable-autodepend --enable-gcc-warnings --enable-better-debugging --with-x-toolkit=no --disable-dependency-tracking --with-ns
        make only_temacs
        cd lisp && make update-subdirs
    - run: make all_only_c
      if: "${{ success() }}"
    - name: Build docs
      if: "${{ success() }}"
      run: |
        if test -d doc && test -x "$(which makeinfo)" && test -x "$(which nproc)"; then \
          echo "using $(which makeinfo) for makeinfo with the following version info: $(makeinfo --version)"; \
          brew install texlive; \
          make -j"$(nproc)" -C doc || (make -C doc/emacs && make -C doc/lispintro && make -C doc/lispref && make -C doc/man); \
          if [ $? -ge 1 ]; then \
            echo "giving doc/misc another try"; \
            pushd doc/misc; \
            make echo-info; \
            make dvi; \
            make html; \
            make pdf; \
            make ps; \
            make dist; \
            popd; \
          else \
            echo "so much for doc/misc..."; \
          fi; \
        else \
          echo "skipping building docs..."; \
        fi
    - name: Apple stuff
      if: "${{ success() }}"
      run: |
        make install_source
        make -ki apple_helper_executables
        make apple_check
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - clang
        - gcc
