name: cooljeanius/emacs
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.1
#     # 'Transformers::TravisCI::Scripts::Dependencies' dependencies are currently unsupported
#     # 'compiler' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: sudo apt-get update -qq
    - run: DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -y -qq -o=Dpkg::Use-Pty=0 libc-dev gcc make autoconf automake libncurses-dev gobjc gobjc++ gobjc-multilib gobjc++-multilib autopoint
    - run: |
        sh ./autogen.sh
        ./configure --without-makeinfo --without-gif --without-gnutls --enable-silent-rules --disable-autodepend --without-imagemagick --enable-gcc-warnings --with-x-toolkit=no --with-xpm=no --disable-openmp
        make only_temacs
    - run: make all_only_c
      if: "${{ success() }}"
    - name: Build docs
      if: "${{ success() }}"
      run: |
        if test -d doc && test -x "$(which makeinfo)"; then \
          echo "using $(which makeinfo) for makeinfo with the following version info: $(makeinfo --version)"; \
          sudo apt-get install texlive ghostscript texlive-luatex texlive-pstricks chktex dvidvi dvipng latexdiff latexmk dot2tex texlive-latex-extra; \
          make -C doc || (make -C doc/emacs && make -C doc/lispintro && make -C doc/lispref && make -C doc/man && make -C doc/misc); \
        fi
    strategy:
      matrix:
        compiler:
        - clang
        - gcc
